- hosts: servers
  remote_user: jcavallo
  tasks:
    - name: Copying Go source code
      become: true 
      copy:
        src: /Users/jamescavallo/Desktop/go1.17.7.linux-amd64.tar.gz
        dest: /users/jcavallo
    - name: Creates directory
      file:
        path: /users/jcavallo/local/go
        state: directory
    - name: Install Go
      command: rm -rf /users/jcavallo/local/go 
    - name: Install Go pt2
      command: tar -C /users/jcavallo/local -xzf /users/jcavallo/go1.17.7.linux-amd64.tar.gz
    - name : Set Go path
      command: export PATH=$PATH:/users/jcavallo/local/go/bin
    - name : Install Someta on all Hosts
      command: go install github.com/jsommers/someta@latest
    - name: Clone a repo with separate git directory
      git:
        repo: https://github.com/jsommers/ELF.git
        dest: /users/jcavallo/
    - name : Run Cloudlab Setup Scipt ~ this may take some time
      command: ./users/jcavallo/ELF/exptscripts/cloudlab_setup.sh
    
