- hosts: servers
  remote_user: jcavallo
  become: yes
  tasks:
    - name: Download Go Source
      get_url:
        url: https://go.dev/dl/go1.17.7.linux-amd64.tar.gz
        dest: /users/jcavallo/go1.17.7.linux-amd64.tar.gz
        mode: '0440'
    - name: Create directory
      file:
        path: /users/jcavallo/local/go
        state: directory
    - name: Install Go
      command: rm -rf /users/jcavallo/local/go 
    - name: Install Go pt2
      command: tar -C /users/jcavallo/local -xzf /users/jcavallo/go1.17.7.linux-amd64.tar.gz
    - name : Install Someta on all Hosts
      command: chdir=/users/jcavallo/local/go/bin ./go install github.com/jsommers/someta@latest
    - name: Clone a repo with separate git directory
      git:
        repo: https://github.com/jsommers/ELF.git
        dest: /users/jcavallo/ELF
    - name: Give insecure permissions to an existing file
      file:
        path: /users/jcavallo/ELF/exptscripts/cloudlab_setup.sh
        mode: '0555'
    - name: Remove the rate limit on all hosts
      command: sysctl -w net.ipv4.icmp_ratelimit=0
      become: yes
      become_user: root
    - name : Run Setup on the "in" node (This may take a while)
      become: yes
      become_user: root
      shell: /users/jcavallo/ELF/exptscripts/cloudlab_setup.sh
      when: ansible_hostname == 'server1' #this is the "in" node
      
    
